name: Nickysfixer
version: ${project.version}
main: me.nickyadmin.nickysfixer.Main
api-version: 1.16
authors: [ NickyAdmin ]
description: nickysfixer for 1.16.5

commands:
  nickysfixer:
    aliases: [nf, nickysfixes, n]
  pop:
  server: